### ISSUE TITLE
CET 1.31.x and 1.32.x, REDEngineErrorReporter.exe crashes on every game application startup.

### ISSUE THREAD

**Issue by anygoodname** [maximegmd/CyberEngineTweaks#934]
Hello,
 
REDEngineErrorReporter.exe crashes on every game application startup with the version.dll v6.0.0 installed in the ..\Cyberpunk 2077\bin\x64 folder.
The game application itself is unaffected so severity level is down to irritating crash messages in this case.
I tracked it down to the version.dll file on a clean game install (disabling cyber_engine_tweaks.asi does not help so it's not the culprit)
It seems to be caused by some debugging code failing as the error message details it to:

An unhandled win32 exception occurred in [8184] REDEngineErrorReporter.exe. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

As a workaround I disabled the REDEngineErrorReporter.exe by renaming the file to stop the annoying messages, however I believe there is something in the version.dll that should be amended.

Regards.
Anygoodname.
![Screenshot (6534)](https://github.com/maximegmd/CyberEngineTweaks/assets/89723772/e65d999b-b73e-4402-ac36-f849f3f05ea4)

**Comment by anygoodname** [comment]
Update: possibly related to Visual Studio leftovers:

**Comment by anygoodname** [comment]
Same issue in CET 1.32.0 and 1.32.1

**Comment by leutnantlurch** [comment]
Same here:
AppName REDEngineErrorReporter.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 65f416ce 
  ModuleName VERSION.dll 
  ModuleVersion 6.0.0.0 
  ModuleTimeStamp 65e1b757 
  ExceptionCode c0000409 
  FaultingOffset 000000000006d88d 
  ProcessId 0x8074 
  ProcessCreationTime 0x1da7bd7eb0e5ead 
  AppPath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\REDEngineErrorReporter.exe 
  ModulePath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\VERSION.dll 
  IntegratorReportId a7727eb8-1853-488a-b284-aaf39efeedd7 
  PackageFullName  
  PackageRelativeAppId  


  AppName REDEngineErrorReporter.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 65f416ce 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.3235 
  ModuleTimeStamp 2b72307b 
  ExceptionCode e06d7363 
  FaultingOffset 0000000000065b0c 
  ProcessId 0x8074 
  ProcessCreationTime 0x1da7bd7eb0e5ead 
  AppPath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\REDEngineErrorReporter.exe 
  ModulePath C:\WINDOWS\System32\KERNELBASE.dll 
  IntegratorReportId ed060707-d03e-4551-9408-709896a7f970 
  PackageFullName  
  PackageRelativeAppId  
----------------------------
  AppName REDEngineErrorReporter.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 65f416ce 
  ModuleName VERSION.dll 
  ModuleVersion 6.0.0.0 
  ModuleTimeStamp 65e1b757 
  ExceptionCode c0000409 
  FaultingOffset 000000000006d88d 
  ProcessId 0x8294 
  ProcessCreationTime 0x1da7bd3443ba0b2 
  AppPath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\REDEngineErrorReporter.exe 
  ModulePath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\VERSION.dll 
  IntegratorReportId bf6015bf-5a35-4480-bd03-fe567368a36c 
  PackageFullName  
  PackageRelativeAppId  

  AppName REDEngineErrorReporter.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 65f416ce 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.3235 
  ModuleTimeStamp 2b72307b 
  ExceptionCode e06d7363 
  FaultingOffset 0000000000065b0c 
  ProcessId 0x8294 
  ProcessCreationTime 0x1da7bd3443ba0b2 
  AppPath C:\Spiele\GOG Games\Cyberpunk 2077\bin\x64\REDEngineErrorReporter.exe 
  ModulePath C:\WINDOWS\System32\KERNELBASE.dll 
  IntegratorReportId 71936634-c0dc-4cca-add5-e22ccd357dbe 
  PackageFullName  
  PackageRelativeAppId

**Comment by AussiePatriot** [comment]
> Hello,
> 
> REDEngineErrorReporter.exe crashes on every game application startup with the version.dll v6.0.0 installed in the ..\Cyberpunk 2077\bin\x64 folder. The game application itself is unaffected so severity level is down to irritating crash messages in this case. I tracked it down to the version.dll file on a clean game install (disabling cyber_engine_tweaks.asi does not help so it's not the culprit) It seems to be caused by some debugging code failing as the error message details it to:
> 
> An unhandled win32 exception occurred in [8184] REDEngineErrorReporter.exe. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.
> 
> As a workaround I disabled the REDEngineErrorReporter.exe by renaming the file to stop the annoying messages, however I believe there is something in the version.dll that should be amended.
> 
> Regards. Anygoodname. ![Screenshot (6534)](https://private-user-images.githubusercontent.com/89723772/310234574-e65d999b-b73e-4402-ac36-f849f3f05ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjk1MjcsIm5iZiI6MTcxMjA2OTIyNywicGF0aCI6Ii84OTcyMzc3Mi8zMTAyMzQ1NzQtZTY1ZDk5OWItYjczZS00NDAyLWFjMzYtZjg0OWYzZjA1ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0NDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzdmNGM5ZDdlOGVlNjJkM2I4NjdjNTAyZTYxYjI0NGUxZmQwNmFhNjdlNTNjOTE3NzY1NDVkYmQ5MmJmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mRrTYRou1el1ts3bW5FZgScpakyUyA1qxJAkemHeAA)

I also get these exact errors. Version.dll is a file created by CET correct? if thats the case then only the creator of CET would be able to fix it?

**Comment by WSSDude** [comment]
Version.dll is Ultimate ASI Loader. You may try to download latest release of it if it doesnt help by a chance if that is causing the crash seemingly.

**Comment by anygoodname** [comment]
> https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/v7.1.0
> 
> If it helps, we can bump version we use (I think we currently use 5.0 or something like that)

Thank you.
Unfortunately none of the versions 5.6 up worked for me - while they try to load the asi, it all ends up in in a fatal error and the game application collapsing on that:
![Screenshot (6600)](https://github.com/maximegmd/CyberEngineTweaks/assets/89723772/304babad-3abf-4b3d-a579-d88a256dae50)

**Comment by AussiePatriot** [comment]
Do I simply add the .dll file to the same dir as the original version.dll file and rename it to 'version.dll'?

**Comment by AussiePatriot** [comment]
Yes I am the same, all fatal error when trying to use 6.3 to latest 7.1

**Comment by maximegmd** [comment]
You must use the one packed with CET, it's a fork. https://github.com/maximegmd/Ultimate-ASI-Loader

**Comment by anygoodname** [comment]
So there is no other version.dll than the one already included in the 1.32.1 distribution?

**Comment by WSSDude** [comment]
Yeah, and it seems this is latest one. Had not noticed we switched to custom fork, wouldn't suggest it. Guess maybe we have sth wrong in the fork? :suspect: I dont think we had this issue before with vanilla ASI loader.

**Comment by anygoodname** [comment]
It started with the CET 1.31 when switched back to asi.

**Comment by maximegmd** [comment]
Can you try this dll:
[version.zip](https://github.com/maximegmd/CyberEngineTweaks/files/14874185/version.zip)

**Comment by WSSDude** [comment]
Hm, wanted to test if I can replicate this on Steam Deck by a chance (as I have nothing better at hand atm) and I can't, even with former release. Funny when Linux works better than Windows...

**Comment by anygoodname** [comment]
> Can you try this dll: [version.zip](https://github.com/maximegmd/CyberEngineTweaks/files/14874185/version.zip)

Barring a binge error message (screenshot below) at the process startup, it all seems to work fine.
The REDEngineErrorReporter.exe works fine too.
So it seems like a good candidate.
![Screenshot (6605)](https://github.com/maximegmd/CyberEngineTweaks/assets/89723772/5a6f9810-c343-436e-a2da-15682e6b8eff)

**Comment by maximegmd** [comment]
Fixed in v1.32.2, uploading once the build finishes :)

**Comment by anygoodname** [comment]
Thanks a lot! :)

**Comment by maximegmd** [comment]
https://github.com/maximegmd/CyberEngineTweaks/releases/tag/v1.32.2

**Comment by AussiePatriot** [comment]
I've just woken up its morning here, I'll check out the new update and see how we go :D

**Comment by AussiePatriot** [comment]
Well, I got another crasdh to desktop after playing maybe about 30 mins, this time however nothing reported in windows event viewer or from RedEngineErrorReporter. So thats a good sign the updated CET is working. But frustrating that crashes still happen with nothing to go on.

**Comment by anygoodname** [comment]
This case is about REDEngineErrorReporter.exe crashing on version.dll startup which has been fixed in the CET 1.32.2.
If you experience other issues, please open a separate case.
This case is closed as solved now.

**Comment by TacoDog311** [comment]
I'm getting "unable to load cyber engine tweaks.asi. error 998" using 1.32.3, reverting back to 1.32.2 loaded correctly.

**Comment by maximegmd** [comment]
read the instructions.
